const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--autoplay-policy=user-gesture-required']});
const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{window.__starts=[];window.__buffers=[];const start=AudioBufferSourceNode.prototype.start;AudioBufferSourceNode.prototype.start=function(...args){window.__starts.push(args[0]);window.__buffers.push(this.buffer);return start.apply(this,args)}});
await page.goto('http://127.0.0.1:8765');await page.locator('.glyph').first().waitFor();assert.equal(await page.locator('.glyph').count(),9);assert.equal(await page.evaluate(()=>playerDiagnostics().contextState),undefined);
await page.screenshot({path:'/tmp/liberandos-desktop.png'});await page.locator('.glyph').first().click();await page.waitForFunction(()=>playerDiagnostics().ready,null,{timeout:45000});
for(let i=1;i<9;i++)await page.locator('.glyph').nth(i).click();assert.equal(await page.locator('#status').textContent(),'SIGNAL RECOVERED');
const diagnostics=await page.evaluate(()=>playerDiagnostics());assert.equal(diagnostics.sourceCount,9);assert.equal(diagnostics.contextState,'running');assert.equal(await page.evaluate(()=>new Set(__starts).size),1);assert.equal(await page.evaluate(()=>new Set(__buffers.map(b=>b.length)).size),1);
const seam=await page.evaluate(async()=>{const n=__buffers[0].length,ctx=new OfflineAudioContext(2,n*2,__buffers[0].sampleRate);__buffers.forEach(buffer=>{const s=ctx.createBufferSource();s.buffer=buffer;s.loop=true;s.connect(ctx.destination);s.start(0)});const r=await ctx.startRendering();let repeatError=0,seamJump=0;for(let c=0;c<2;c++){const d=r.getChannelData(c);seamJump=Math.max(seamJump,Math.abs(d[n]-d[n-1]));for(let i=0;i<n;i++)repeatError=Math.max(repeatError,Math.abs(d[i]-d[i+n]));}return{repeatError,seamJump}});assert.ok(seam.repeatError<1e-6);assert.ok(seam.seamJump<.05);
await page.locator('#transport').click();await page.waitForFunction(()=>playerDiagnostics().contextState==='suspended');await page.locator('#transport').click();await page.waitForFunction(()=>playerDiagnostics().contextState==='running');await page.locator('.glyph').first().click();assert.equal(await page.locator('#status').textContent(),'8/9 CHANNELS RECOVERED');for(let i=1;i<9;i++)await page.locator('.glyph').nth(i).click();assert.equal(await page.locator('#status').textContent(),'0/9 CHANNELS RECOVERED');await page.locator('.glyph').first().focus();await page.keyboard.press('Space');assert.equal(await page.locator('.glyph').first().getAttribute('aria-pressed'),'true');
await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const boxes=await page.locator('.glyph').evaluateAll(bs=>bs.map(b=>{const r=b.getBoundingClientRect();return{w:r.width,h:r.height}}));assert.ok(boxes.every(b=>b.w>=44&&b.h>=44));await page.screenshot({path:'/tmp/liberandos-mobile.png'});await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.locator('.glyph svg').first().evaluate(el=>getComputedStyle(el).animationName),'none');
const p=await browser.newPage();await p.route('**/audio/**',r=>r.abort());await p.goto('http://127.0.0.1:8765');await p.locator('.glyph').first().click();await p.locator('#retry').waitFor();await p.unroute('**/audio/**');await p.locator('#retry').click();await p.waitForFunction(()=>playerDiagnostics().ready,null,{timeout:45000});assert.equal(await p.locator('.glyph').first().getAttribute('aria-pressed'),'true');assert.deepEqual(errors,[]);
const result={diagnostics,seam,checks:['no autoplay','nine shared-timestamp sources','identical loop lengths','two-cycle offline render','all-on completion','all-off','gain toggles','pause/resume','keyboard','mobile targets/overflow','reduced motion','failed-load retry','no page errors']};fs.writeFileSync('test-results.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
